In [1]:
import pandas as pd

data = {
    "OrderID": range(1001, 1031),
    "Date": [
        "2026-01-03", "2026-01-05", "2026-01-07", "2026-01-10", "2026-01-12",
        "2026-01-15", "2026-01-18", "2026-01-21", "2026-01-25", "2026-01-28",
        "2026-02-02", "2026-02-04", "2026-02-08", "2026-02-11", "2026-02-14",
        "2026-02-17", "2026-02-20", "2026-02-23", "2026-02-25", "2026-02-27",
        "2026-03-01", "2026-03-04", "2026-03-07", "2026-03-10", "2026-03-13",
        "2026-03-16", "2026-03-19", "2026-03-22", "2026-03-25", "2026-03-28"
    ],
    "City": [
        "Rajkot", "Ahmedabad", "Surat", "Rajkot", "Ahmedabad",
        "Surat", "Rajkot", "Ahmedabad", "Surat", "Rajkot",
        "Ahmedabad", "Surat", "Rajkot", "Ahmedabad", "Surat",
        "Rajkot", "Ahmedabad", "Surat", "Rajkot", "Ahmedabad",
        "Surat", "Rajkot", "Ahmedabad", "Surat", "Rajkot",
        "Ahmedabad", "Surat", "Rajkot", "Ahmedabad", "Surat"
    ],
    "Product": [
        "Pizza", "Burger", "Pasta", "Burger", "Pizza",
        "Pasta", "Pizza", "Pasta", "Burger", "Pizza",
        "Burger", "Pizza", "Pasta", "Pizza", "Burger",
        "Pasta", "Pizza", "Pasta", "Burger", "Pizza",
        "Pizza", "Burger", "Pasta", "Pizza", "Pasta",
        "Burger", "Pizza", "Pizza", "Burger", "Pasta"
    ],
    "Category": [
        "Main Course", "Fast Food", "Main Course", "Fast Food", "Main Course",
        "Main Course", "Main Course", "Main Course", "Fast Food", "Main Course",
        "Fast Food", "Main Course", "Main Course", "Main Course", "Fast Food",
        "Main Course", "Main Course", "Main Course", "Fast Food", "Main Course",
        "Main Course", "Fast Food", "Main Course", "Main Course", "Main Course",
        "Fast Food", "Main Course", "Main Course", "Fast Food", "Main Course"
    ],
    "Quantity": [
        2, 3, 1, 4, 2, 2, 3, 1, 2, 1,
        5, 2, 3, 1, 4, 2, 3, 2, 1, 2,
        4, 2, 3, 1, 2, 3, 2, 5, 2, 1
    ],
    "UnitPrice": [
        300, 150, 250, 150, 300, 250, 300, 250, 150, 300,
        150, 300, 250, 300, 150, 250, 300, 250, 150, 300,
        300, 150, 250, 300, 250, 150, 300, 300, 150, 250
    ],
    "Employee": [
        "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit",
        "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha",
        "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul"
    ],
    "PaymentMethod": [
        "UPI", "Cash", "Card", "UPI", "Card", "Cash", "UPI", "UPI", "Cash", "Card",
        "UPI", "Card", "Cash", "UPI", "Cash", "Card", "UPI", "Cash", "UPI", "Card",
        "UPI", "Cash", "Card", "UPI", "Cash", "Card", "UPI", "UPI", "Cash", "Card"
    ],
    "Status": [
        "Delivered", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Delivered", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Delivered", "Delivered", "Delivered", "Cancelled", "Delivered",
        "Delivered", "Delivered", "Delivered", "Cancelled", "Delivered",
        "Delivered", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Delivered", "Delivered", "Delivered", "Delivered", "Cancelled"
    ]
}

In [3]:
df=pd.DataFrame(data)
print(df)

    OrderID        Date       City Product     Category  Quantity  UnitPrice  \
0      1001  2026-01-03     Rajkot   Pizza  Main Course         2        300
1      1002  2026-01-05  Ahmedabad  Burger    Fast Food         3        150
2      1003  2026-01-07      Surat   Pasta  Main Course         1        250
3      1004  2026-01-10     Rajkot  Burger    Fast Food         4        150
4      1005  2026-01-12  Ahmedabad   Pizza  Main Course         2        300
5      1006  2026-01-15      Surat   Pasta  Main Course         2        250
6      1007  2026-01-18     Rajkot   Pizza  Main Course         3        300
7      1008  2026-01-21  Ahmedabad   Pasta  Main Course         1        250
8      1009  2026-01-25      Surat  Burger    Fast Food         2        150
9      1010  2026-01-28     Rajkot   Pizza  Main Course         1        300
10     1011  2026-02-02  Ahmedabad  Burger    Fast Food         5        150
11     1012  2026-02-04      Surat   Pizza  Main Course         2        300
12     1013  2026-02-08     Rajkot   Pasta  Main Course         3        250
13     1014  2026-02-11  Ahmedabad   Pizza  Main Course         1        300
14     1015  2026-02-14      Surat  Burger    Fast Food         4        150
15     1016  2026-02-17     Rajkot   Pasta  Main Course         2        250
16     1017  2026-02-20  Ahmedabad   Pizza  Main Course         3        300
17     1018  2026-02-23      Surat   Pasta  Main Course         2        250
18     1019  2026-02-25     Rajkot  Burger    Fast Food         1        150
19     1020  2026-02-27  Ahmedabad   Pizza  Main Course         2        300
20     1021  2026-03-01      Surat   Pizza  Main Course         4        300
21     1022  2026-03-04     Rajkot  Burger    Fast Food         2        150
22     1023  2026-03-07  Ahmedabad   Pasta  Main Course         3        250
23     1024  2026-03-10      Surat   Pizza  Main Course         1        300
24     1025  2026-03-13     Rajkot   Pasta  Main Course         2        250
25     1026  2026-03-16  Ahmedabad  Burger    Fast Food         3        150
26     1027  2026-03-19      Surat   Pizza  Main Course         2        300
27     1028  2026-03-22     Rajkot   Pizza  Main Course         5        300
28     1029  2026-03-25  Ahmedabad  Burger    Fast Food         2        150
29     1030  2026-03-28      Surat   Pasta  Main Course         1        250

   Employee PaymentMethod     Status
0      Amit           UPI  Delivered
1      Neha          Cash  Delivered
2     Rahul          Card  Cancelled
3      Amit           UPI  Delivered
4      Neha          Card  Delivered
5     Rahul          Cash  Delivered
6      Amit           UPI  Delivered
7      Neha           UPI  Cancelled
8     Rahul          Cash  Delivered
9      Amit          Card  Delivered
10     Neha           UPI  Delivered
11    Rahul          Card  Delivered
12     Amit          Cash  Delivered
13     Neha           UPI  Cancelled
14    Rahul          Cash  Delivered
15     Amit          Card  Delivered
16     Neha           UPI  Delivered
17    Rahul          Cash  Delivered
18     Amit           UPI  Cancelled
19     Neha          Card  Delivered
20    Rahul           UPI  Delivered
21     Amit          Cash  Delivered
22     Neha          Card  Cancelled
23    Rahul           UPI  Delivered
24     Amit          Cash  Delivered
25     Neha          Card  Delivered
26    Rahul           UPI  Delivered
27     Amit           UPI  Delivered
28     Neha          Cash  Delivered
29    Rahul          Card  Cancelled

In [5]:
# print(df.head(2))
# print(df.tail(2))
# print(df.sample(2))

In [6]:
df["Date"] = pd.to_datetime(df["Date"])
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print("Dataset shape:", df.shape)
display(df.head(10))
display(df)

Dataset shape: (30, 11)

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600
1,1002,2026-01-05,Ahmedabad,Burger,Fast Food,3,150,Neha,Cash,Delivered,450
2,1003,2026-01-07,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600
4,1005,2026-01-12,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600
5,1006,2026-01-15,Surat,Pasta,Main Course,2,250,Rahul,Cash,Delivered,500
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900
7,1008,2026-01-21,Ahmedabad,Pasta,Main Course,1,250,Neha,UPI,Cancelled,250
8,1009,2026-01-25,Surat,Burger,Fast Food,2,150,Rahul,Cash,Delivered,300
9,1010,2026-01-28,Rajkot,Pizza,Main Course,1,300,Amit,Card,Delivered,300

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600
1,1002,2026-01-05,Ahmedabad,Burger,Fast Food,3,150,Neha,Cash,Delivered,450
2,1003,2026-01-07,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600
4,1005,2026-01-12,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600
5,1006,2026-01-15,Surat,Pasta,Main Course,2,250,Rahul,Cash,Delivered,500
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900
7,1008,2026-01-21,Ahmedabad,Pasta,Main Course,1,250,Neha,UPI,Cancelled,250
8,1009,2026-01-25,Surat,Burger,Fast Food,2,150,Rahul,Cash,Delivered,300
9,1010,2026-01-28,Rajkot,Pizza,Main Course,1,300,Amit,Card,Delivered,300
10,1011,2026-02-02,Ahmedabad,Burger,Fast Food,5,150,Neha,UPI,Delivered,750
11,1012,2026-02-04,Surat,Pizza,Main Course,2,300,Rahul,Card,Delivered,600
12,1013,2026-02-08,Rajkot,Pasta,Main Course,3,250,Amit,Cash,Delivered,750
13,1014,2026-02-11,Ahmedabad,Pizza,Main Course,1,300,Neha,UPI,Cancelled,300
14,1015,2026-02-14,Surat,Burger,Fast Food,4,150,Rahul,Cash,Delivered,600
15,1016,2026-02-17,Rajkot,Pasta,Main Course,2,250,Amit,Card,Delivered,500
16,1017,2026-02-20,Ahmedabad,Pizza,Main Course,3,300,Neha,UPI,Delivered,900
17,1018,2026-02-23,Surat,Pasta,Main Course,2,250,Rahul,Cash,Delivered,500
18,1019,2026-02-25,Rajkot,Burger,Fast Food,1,150,Amit,UPI,Cancelled,150
19,1020,2026-02-27,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600
20,1021,2026-03-01,Surat,Pizza,Main Course,4,300,Rahul,UPI,Delivered,1200
21,1022,2026-03-04,Rajkot,Burger,Fast Food,2,150,Amit,Cash,Delivered,300
22,1023,2026-03-07,Ahmedabad,Pasta,Main Course,3,250,Neha,Card,Cancelled,750
23,1024,2026-03-10,Surat,Pizza,Main Course,1,300,Rahul,UPI,Delivered,300
24,1025,2026-03-13,Rajkot,Pasta,Main Course,2,250,Amit,Cash,Delivered,500
25,1026,2026-03-16,Ahmedabad,Burger,Fast Food,3,150,Neha,Card,Delivered,450
26,1027,2026-03-19,Surat,Pizza,Main Course,2,300,Rahul,UPI,Delivered,600
27,1028,2026-03-22,Rajkot,Pizza,Main Course,5,300,Amit,UPI,Delivered,1500
28,1029,2026-03-25,Ahmedabad,Burger,Fast Food,2,150,Neha,Cash,Delivered,300
29,1030,2026-03-28,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250

In [11]:
print(df.shape)
print(df.size)
print(df.info())

(30, 11)
330
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        30 non-null     int64
 1   Date           30 non-null     datetime64[ns]
 2   City           30 non-null     object
 3   Product        30 non-null     object
 4   Category       30 non-null     object
 5   Quantity       30 non-null     int64
 6   UnitPrice      30 non-null     int64
 7   Employee       30 non-null     object
 8   PaymentMethod  30 non-null     object
 9   Status         30 non-null     object
 10  Revenue        30 non-null     int64
dtypes: datetime64[ns](1), int64(4), object(6)
memory usage: 2.7+ KB
None

In [12]:
print(df.head(5))

   OrderID       Date       City Product     Category  Quantity  UnitPrice  \
0     1001 2026-01-03     Rajkot   Pizza  Main Course         2        300
1     1002 2026-01-05  Ahmedabad  Burger    Fast Food         3        150
2     1003 2026-01-07      Surat   Pasta  Main Course         1        250
3     1004 2026-01-10     Rajkot  Burger    Fast Food         4        150
4     1005 2026-01-12  Ahmedabad   Pizza  Main Course         2        300

  Employee PaymentMethod     Status  Revenue
0     Amit           UPI  Delivered      600
1     Neha          Cash  Delivered      450
2    Rahul          Card  Cancelled      250
3     Amit           UPI  Delivered      600
4     Neha          Card  Delivered      600

In [16]:
df["Status"].value_counts()

Status
Delivered    24
Cancelled     6
Name: count, dtype: int64

In [17]:
df.groupby('City')['Revenue'].sum()

City
Ahmedabad    5350
Rajkot       6100
Surat        5100
Name: Revenue, dtype: int64

In [19]:
df.groupby(['City','Product'])['Revenue'].sum()

City       Product
Ahmedabad  Burger     1950
           Pasta      1000
           Pizza      2400
Rajkot     Burger     1050
           Pasta      1750
           Pizza      3300
Surat      Burger      900
           Pasta      1500
           Pizza      2700
Name: Revenue, dtype: int64

In [20]:
# Appply multiple aggregation function 


df.groupby('City')['Revenue'].agg(
    ['sum','max','min']
)

            sum   max  min
City
Ahmedabad  5350   900  250
Rajkot     6100  1500  150
Surat      5100  1200  250

In [22]:
# Different Aggregation for different column

df.groupby('City').agg(
    total_revenue=('Revenue','sum'),
    average_revenue=("Revenue", "mean"),
    total_quantity=("Quantity", "sum"),
    order_count=("OrderID", "count")
)

           total_revenue  average_revenue  total_quantity  order_count
City
Ahmedabad           5350            535.0              25           10
Rajkot              6100            610.0              25           10
Surat               5100            510.0              21           10

In [26]:
df["Month"] = df["Date"].dt.month_name()
df.groupby('Month')['Revenue'].sum()

Month
February    5650
January     4750
March       6150
Name: Revenue, dtype: int64

In [27]:
df[(df['City']=="Rajkot")&(df['Revenue']>500)]

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue,Month
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600,January
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600,January
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900,January
12,1013,2026-02-08,Rajkot,Pasta,Main Course,3,250,Amit,Cash,Delivered,750,February
27,1028,2026-03-22,Rajkot,Pizza,Main Course,5,300,Amit,UPI,Delivered,1500,March

In [29]:
df[df["PaymentMethod"].isin(["UPI", "Card"])]

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue,Month
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600,January
2,1003,2026-01-07,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250,January
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600,January
4,1005,2026-01-12,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600,January
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900,January
7,1008,2026-01-21,Ahmedabad,Pasta,Main Course,1,250,Neha,UPI,Cancelled,250,January
9,1010,2026-01-28,Rajkot,Pizza,Main Course,1,300,Amit,Card,Delivered,300,January
10,1011,2026-02-02,Ahmedabad,Burger,Fast Food,5,150,Neha,UPI,Delivered,750,February
11,1012,2026-02-04,Surat,Pizza,Main Course,2,300,Rahul,Card,Delivered,600,February
13,1014,2026-02-11,Ahmedabad,Pizza,Main Course,1,300,Neha,UPI,Cancelled,300,February
15,1016,2026-02-17,Rajkot,Pasta,Main Course,2,250,Amit,Card,Delivered,500,February
16,1017,2026-02-20,Ahmedabad,Pizza,Main Course,3,300,Neha,UPI,Delivered,900,February
18,1019,2026-02-25,Rajkot,Burger,Fast Food,1,150,Amit,UPI,Cancelled,150,February
19,1020,2026-02-27,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600,February
20,1021,2026-03-01,Surat,Pizza,Main Course,4,300,Rahul,UPI,Delivered,1200,March
22,1023,2026-03-07,Ahmedabad,Pasta,Main Course,3,250,Neha,Card,Cancelled,750,March
23,1024,2026-03-10,Surat,Pizza,Main Course,1,300,Rahul,UPI,Delivered,300,March
25,1026,2026-03-16,Ahmedabad,Burger,Fast Food,3,150,Neha,Card,Delivered,450,March
26,1027,2026-03-19,Surat,Pizza,Main Course,2,300,Rahul,UPI,Delivered,600,March
27,1028,2026-03-22,Rajkot,Pizza,Main Course,5,300,Amit,UPI,Delivered,1500,March
29,1030,2026-03-28,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250,March

In [30]:
print(df.isna().sum())
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

OrderID          0
Date             0
City             0
Product          0
Category         0
Quantity         0
UnitPrice        0
Employee         0
PaymentMethod    0
Status           0
Revenue          0
Month            0
dtype: int64

In [31]:
import numpy as np

np.random.seed(42)

days = 30

daily_sales = np.random.randint(10_000, 50_001, size=days)

profit_margin = np.random.uniform(0.10, 0.25, size=days)

profit = daily_sales * profit_margin

print("Sales:")
print(daily_sales,end='\n\n')

print("Profit Margin:")
print(profit_margin,end='\n\n')

print("Profit:")
print(profit,end='\n\n')

Sales:
[25795 10860 48158 21284 16265 26850 47194 31962 26023 11685 10769 12433
 15311 47819 49188 27568 29769 38693 16396 37480 35658 28942 28431 12747
 10189 29118 45773 11899 11267 41551]

Profit Margin:
[0.17001443 0.22899106 0.20204613 0.16757489 0.10198974 0.24133026
 0.18449323 0.15781248 0.10239494 0.13463407 0.13615382 0.20248953
 0.1914995  0.22497924 0.1260047  0.15865909 0.12733541 0.21330421
 0.16377338 0.13119125 0.18515505 0.10469699 0.22634272 0.16746312
 0.15927254 0.23899883 0.2090908  0.14898112 0.1855666  0.17812514]

Profit:
[ 4385.5223247   2486.84292257  9730.1375665   3566.66391184
  1658.86318899  6479.71757102  8706.97362295  5044.00233813
  2664.62346723  1573.19915286  1466.24048655  2517.55229943
  2932.0488241  10758.28212265  6197.91908651  4373.91382444
  3790.6479146   8253.37985741  2685.22835772  4917.04802864
  6602.25874341  3030.14039654  6435.14976398  2134.65239071
  1622.82786319  6959.16792813  9570.71315995  1772.7262912
  2090.77883894  7401.27765075]

In [32]:
import pandas as pd

dates = pd.date_range(
    start="2024-01-01",
    end="2024-01-30"
)

regions = np.array([ "North", "South", "East", "West" ])

region_data = np.array([ regions[ i % 4 ] for i in range(30) ])

df = pd.DataFrame({
    "Date": dates,
    "Region": region_data,
    "Sales": daily_sales,
    "Profit_Margin": profit_margin,
    "Profit": profit
})

print(df)

         Date Region  Sales  Profit_Margin        Profit
0  2024-01-01  North  25795       0.170014   4385.522325
1  2024-01-02  South  10860       0.228991   2486.842923
2  2024-01-03   East  48158       0.202046   9730.137566
3  2024-01-04   West  21284       0.167575   3566.663912
4  2024-01-05  North  16265       0.101990   1658.863189
5  2024-01-06  South  26850       0.241330   6479.717571
6  2024-01-07   East  47194       0.184493   8706.973623
7  2024-01-08   West  31962       0.157812   5044.002338
8  2024-01-09  North  26023       0.102395   2664.623467
9  2024-01-10  South  11685       0.134634   1573.199153
10 2024-01-11   East  10769       0.136154   1466.240487
11 2024-01-12   West  12433       0.202490   2517.552299
12 2024-01-13  North  15311       0.191499   2932.048824
13 2024-01-14  South  47819       0.224979  10758.282123
14 2024-01-15   East  49188       0.126005   6197.919087
15 2024-01-16   West  27568       0.158659   4373.913824
16 2024-01-17  North  29769       0.127335   3790.647915
17 2024-01-18  South  38693       0.213304   8253.379857
18 2024-01-19   East  16396       0.163773   2685.228358
19 2024-01-20   West  37480       0.131191   4917.048029
20 2024-01-21  North  35658       0.185155   6602.258743
21 2024-01-22  South  28942       0.104697   3030.140397
22 2024-01-23   East  28431       0.226343   6435.149764
23 2024-01-24   West  12747       0.167463   2134.652391
24 2024-01-25  North  10189       0.159273   1622.827863
25 2024-01-26  South  29118       0.238999   6959.167928
26 2024-01-27   East  45773       0.209091   9570.713160
27 2024-01-28   West  11899       0.148981   1772.726291
28 2024-01-29  North  11267       0.185567   2090.778839
29 2024-01-30  South  41551       0.178125   7401.277651

In [33]:
df.describe()

                      Date         Sales  Profit_Margin        Profit
count                   30     30.000000      30.000000     30.000000
mean   2024-01-15 12:00:00  26902.566667       0.172345   4726.949997
min    2024-01-01 00:00:00  10189.000000       0.101990   1466.240487
25%    2024-01-08 06:00:00  13388.000000       0.139361   2494.520267
50%    2024-01-15 12:00:00  27209.000000       0.168795   4082.280870
75%    2024-01-22 18:00:00  37024.500000       0.202379   6571.623450
max    2024-01-30 00:00:00  49188.000000       0.241330  10758.282123
std                    NaN  13184.289888       0.040710   2791.610554

In [38]:
df[df.groupby('Region')]

TypeError: unhashable type: 'DataFrame'

In [40]:
df.count()

Date             30
Region           30
Sales            30
Profit_Margin    30
Profit           30
dtype: int64

In [42]:
df.notna()

    Date  Region  Sales  Profit_Margin  Profit
0   True    True   True           True    True
1   True    True   True           True    True
2   True    True   True           True    True
3   True    True   True           True    True
4   True    True   True           True    True
5   True    True   True           True    True
6   True    True   True           True    True
7   True    True   True           True    True
8   True    True   True           True    True
9   True    True   True           True    True
10  True    True   True           True    True
11  True    True   True           True    True
12  True    True   True           True    True
13  True    True   True           True    True
14  True    True   True           True    True
15  True    True   True           True    True
16  True    True   True           True    True
17  True    True   True           True    True
18  True    True   True           True    True
19  True    True   True           True    True
20  True    True   True           True    True
21  True    True   True           True    True
22  True    True   True           True    True
23  True    True   True           True    True
24  True    True   True           True    True
25  True    True   True           True    True
26  True    True   True           True    True
27  True    True   True           True    True
28  True    True   True           True    True
29  True    True   True           True    True

In [ ]:
import matplotlib.pyplot as plt

plt.plot(df.Date, df.Profit)
plt.title('sales for 1 month')
plt.show()

ModuleNotFoundError: No module named 'matlplotlib'

In [45]:
df = pd.read_csv('./company_sales_data.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: './company_sales_data.csv'