In [1]:
import pandas as pd

data = {
    "OrderID": range(1001, 1031),
    "Date": [
        "2026-01-03", "2026-01-05", "2026-01-07", "2026-01-10", "2026-01-12",
        "2026-01-15", "2026-01-18", "2026-01-21", "2026-01-25", "2026-01-28",
        "2026-02-02", "2026-02-04", "2026-02-08", "2026-02-11", "2026-02-14",
        "2026-02-17", "2026-02-20", "2026-02-23", "2026-02-25", "2026-02-27",
        "2026-03-01", "2026-03-04", "2026-03-07", "2026-03-10", "2026-03-13",
        "2026-03-16", "2026-03-19", "2026-03-22", "2026-03-25", "2026-03-28"
    ],
    "City": [
        "Rajkot", "Ahmedabad", "Surat", "Rajkot", "Ahmedabad",
        "Surat", "Rajkot", "Ahmedabad", "Surat", "Rajkot",
        "Ahmedabad", "Surat", "Rajkot", "Ahmedabad", "Surat",
        "Rajkot", "Ahmedabad", "Surat", "Rajkot", "Ahmedabad",
        "Surat", "Rajkot", "Ahmedabad", "Surat", "Rajkot",
        "Ahmedabad", "Surat", "Rajkot", "Ahmedabad", "Surat"
    ],
    "Product": [
        "Pizza", "Burger", "Pasta", "Burger", "Pizza",
        "Pasta", "Pizza", "Pasta", "Burger", "Pizza",
        "Burger", "Pizza", "Pasta", "Pizza", "Burger",
        "Pasta", "Pizza", "Pasta", "Burger", "Pizza",
        "Pizza", "Burger", "Pasta", "Pizza", "Pasta",
        "Burger", "Pizza", "Pizza", "Burger", "Pasta"
    ],
    "Category": [
        "Main Course", "Fast Food", "Main Course", "Fast Food", "Main Course",
        "Main Course", "Main Course", "Main Course", "Fast Food", "Main Course",
        "Fast Food", "Main Course", "Main Course", "Main Course", "Fast Food",
        "Main Course", "Main Course", "Main Course", "Fast Food", "Main Course",
        "Main Course", "Fast Food", "Main Course", "Main Course", "Main Course",
        "Fast Food", "Main Course", "Main Course", "Fast Food", "Main Course"
    ],
    "Quantity": [
        2, 3, 1, 4, 2, 2, 3, 1, 2, 1,
        5, 2, 3, 1, 4, 2, 3, 2, 1, 2,
        4, 2, 3, 1, 2, 3, 2, 5, 2, 1
    ],
    "UnitPrice": [
        300, 150, 250, 150, 300, 250, 300, 250, 150, 300,
        150, 300, 250, 300, 150, 250, 300, 250, 150, 300,
        300, 150, 250, 300, 250, 150, 300, 300, 150, 250
    ],
    "Employee": [
        "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit",
        "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha",
        "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul", "Amit", "Neha", "Rahul"
    ],
    "PaymentMethod": [
        "UPI", "Cash", "Card", "UPI", "Card", "Cash", "UPI", "UPI", "Cash", "Card",
        "UPI", "Card", "Cash", "UPI", "Cash", "Card", "UPI", "Cash", "UPI", "Card",
        "UPI", "Cash", "Card", "UPI", "Cash", "Card", "UPI", "UPI", "Cash", "Card"
    ],
    "Status": [
        "Delivered", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Delivered", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Delivered", "Delivered", "Delivered", "Cancelled", "Delivered",
        "Delivered", "Delivered", "Delivered", "Cancelled", "Delivered",
        "Delivered", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Delivered", "Delivered", "Delivered", "Delivered", "Cancelled"
    ]
}

In [3]:
df=pd.DataFrame(data)
print(df)

    OrderID        Date       City Product     Category  Quantity  UnitPrice  \
0      1001  2026-01-03     Rajkot   Pizza  Main Course         2        300
1      1002  2026-01-05  Ahmedabad  Burger    Fast Food         3        150
2      1003  2026-01-07      Surat   Pasta  Main Course         1        250
3      1004  2026-01-10     Rajkot  Burger    Fast Food         4        150
4      1005  2026-01-12  Ahmedabad   Pizza  Main Course         2        300
5      1006  2026-01-15      Surat   Pasta  Main Course         2        250
6      1007  2026-01-18     Rajkot   Pizza  Main Course         3        300
7      1008  2026-01-21  Ahmedabad   Pasta  Main Course         1        250
8      1009  2026-01-25      Surat  Burger    Fast Food         2        150
9      1010  2026-01-28     Rajkot   Pizza  Main Course         1        300
10     1011  2026-02-02  Ahmedabad  Burger    Fast Food         5        150
11     1012  2026-02-04      Surat   Pizza  Main Course         2        300
12     1013  2026-02-08     Rajkot   Pasta  Main Course         3        250
13     1014  2026-02-11  Ahmedabad   Pizza  Main Course         1        300
14     1015  2026-02-14      Surat  Burger    Fast Food         4        150
15     1016  2026-02-17     Rajkot   Pasta  Main Course         2        250
16     1017  2026-02-20  Ahmedabad   Pizza  Main Course         3        300
17     1018  2026-02-23      Surat   Pasta  Main Course         2        250
18     1019  2026-02-25     Rajkot  Burger    Fast Food         1        150
19     1020  2026-02-27  Ahmedabad   Pizza  Main Course         2        300
20     1021  2026-03-01      Surat   Pizza  Main Course         4        300
21     1022  2026-03-04     Rajkot  Burger    Fast Food         2        150
22     1023  2026-03-07  Ahmedabad   Pasta  Main Course         3        250
23     1024  2026-03-10      Surat   Pizza  Main Course         1        300
24     1025  2026-03-13     Rajkot   Pasta  Main Course         2        250
25     1026  2026-03-16  Ahmedabad  Burger    Fast Food         3        150
26     1027  2026-03-19      Surat   Pizza  Main Course         2        300
27     1028  2026-03-22     Rajkot   Pizza  Main Course         5        300
28     1029  2026-03-25  Ahmedabad  Burger    Fast Food         2        150
29     1030  2026-03-28      Surat   Pasta  Main Course         1        250

   Employee PaymentMethod     Status
0      Amit           UPI  Delivered
1      Neha          Cash  Delivered
2     Rahul          Card  Cancelled
3      Amit           UPI  Delivered
4      Neha          Card  Delivered
5     Rahul          Cash  Delivered
6      Amit           UPI  Delivered
7      Neha           UPI  Cancelled
8     Rahul          Cash  Delivered
9      Amit          Card  Delivered
10     Neha           UPI  Delivered
11    Rahul          Card  Delivered
12     Amit          Cash  Delivered
13     Neha           UPI  Cancelled
14    Rahul          Cash  Delivered
15     Amit          Card  Delivered
16     Neha           UPI  Delivered
17    Rahul          Cash  Delivered
18     Amit           UPI  Cancelled
19     Neha          Card  Delivered
20    Rahul           UPI  Delivered
21     Amit          Cash  Delivered
22     Neha          Card  Cancelled
23    Rahul           UPI  Delivered
24     Amit          Cash  Delivered
25     Neha          Card  Delivered
26    Rahul           UPI  Delivered
27     Amit           UPI  Delivered
28     Neha          Cash  Delivered
29    Rahul          Card  Cancelled

In [5]:
# print(df.head(2))
# print(df.tail(2))
# print(df.sample(2))

In [6]:
df["Date"] = pd.to_datetime(df["Date"])
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print("Dataset shape:", df.shape)
display(df.head(10))
display(df)

Dataset shape: (30, 11)

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600
1,1002,2026-01-05,Ahmedabad,Burger,Fast Food,3,150,Neha,Cash,Delivered,450
2,1003,2026-01-07,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600
4,1005,2026-01-12,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600
5,1006,2026-01-15,Surat,Pasta,Main Course,2,250,Rahul,Cash,Delivered,500
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900
7,1008,2026-01-21,Ahmedabad,Pasta,Main Course,1,250,Neha,UPI,Cancelled,250
8,1009,2026-01-25,Surat,Burger,Fast Food,2,150,Rahul,Cash,Delivered,300
9,1010,2026-01-28,Rajkot,Pizza,Main Course,1,300,Amit,Card,Delivered,300

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600
1,1002,2026-01-05,Ahmedabad,Burger,Fast Food,3,150,Neha,Cash,Delivered,450
2,1003,2026-01-07,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600
4,1005,2026-01-12,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600
5,1006,2026-01-15,Surat,Pasta,Main Course,2,250,Rahul,Cash,Delivered,500
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900
7,1008,2026-01-21,Ahmedabad,Pasta,Main Course,1,250,Neha,UPI,Cancelled,250
8,1009,2026-01-25,Surat,Burger,Fast Food,2,150,Rahul,Cash,Delivered,300
9,1010,2026-01-28,Rajkot,Pizza,Main Course,1,300,Amit,Card,Delivered,300
10,1011,2026-02-02,Ahmedabad,Burger,Fast Food,5,150,Neha,UPI,Delivered,750
11,1012,2026-02-04,Surat,Pizza,Main Course,2,300,Rahul,Card,Delivered,600
12,1013,2026-02-08,Rajkot,Pasta,Main Course,3,250,Amit,Cash,Delivered,750
13,1014,2026-02-11,Ahmedabad,Pizza,Main Course,1,300,Neha,UPI,Cancelled,300
14,1015,2026-02-14,Surat,Burger,Fast Food,4,150,Rahul,Cash,Delivered,600
15,1016,2026-02-17,Rajkot,Pasta,Main Course,2,250,Amit,Card,Delivered,500
16,1017,2026-02-20,Ahmedabad,Pizza,Main Course,3,300,Neha,UPI,Delivered,900
17,1018,2026-02-23,Surat,Pasta,Main Course,2,250,Rahul,Cash,Delivered,500
18,1019,2026-02-25,Rajkot,Burger,Fast Food,1,150,Amit,UPI,Cancelled,150
19,1020,2026-02-27,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600
20,1021,2026-03-01,Surat,Pizza,Main Course,4,300,Rahul,UPI,Delivered,1200
21,1022,2026-03-04,Rajkot,Burger,Fast Food,2,150,Amit,Cash,Delivered,300
22,1023,2026-03-07,Ahmedabad,Pasta,Main Course,3,250,Neha,Card,Cancelled,750
23,1024,2026-03-10,Surat,Pizza,Main Course,1,300,Rahul,UPI,Delivered,300
24,1025,2026-03-13,Rajkot,Pasta,Main Course,2,250,Amit,Cash,Delivered,500
25,1026,2026-03-16,Ahmedabad,Burger,Fast Food,3,150,Neha,Card,Delivered,450
26,1027,2026-03-19,Surat,Pizza,Main Course,2,300,Rahul,UPI,Delivered,600
27,1028,2026-03-22,Rajkot,Pizza,Main Course,5,300,Amit,UPI,Delivered,1500
28,1029,2026-03-25,Ahmedabad,Burger,Fast Food,2,150,Neha,Cash,Delivered,300
29,1030,2026-03-28,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250

In [11]:
print(df.shape)
print(df.size)
print(df.info())

(30, 11)
330
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        30 non-null     int64
 1   Date           30 non-null     datetime64[ns]
 2   City           30 non-null     object
 3   Product        30 non-null     object
 4   Category       30 non-null     object
 5   Quantity       30 non-null     int64
 6   UnitPrice      30 non-null     int64
 7   Employee       30 non-null     object
 8   PaymentMethod  30 non-null     object
 9   Status         30 non-null     object
 10  Revenue        30 non-null     int64
dtypes: datetime64[ns](1), int64(4), object(6)
memory usage: 2.7+ KB
None

In [12]:
print(df.head(5))

   OrderID       Date       City Product     Category  Quantity  UnitPrice  \
0     1001 2026-01-03     Rajkot   Pizza  Main Course         2        300
1     1002 2026-01-05  Ahmedabad  Burger    Fast Food         3        150
2     1003 2026-01-07      Surat   Pasta  Main Course         1        250
3     1004 2026-01-10     Rajkot  Burger    Fast Food         4        150
4     1005 2026-01-12  Ahmedabad   Pizza  Main Course         2        300

  Employee PaymentMethod     Status  Revenue
0     Amit           UPI  Delivered      600
1     Neha          Cash  Delivered      450
2    Rahul          Card  Cancelled      250
3     Amit           UPI  Delivered      600
4     Neha          Card  Delivered      600

In [16]:
df["Status"].value_counts()

Status
Delivered    24
Cancelled     6
Name: count, dtype: int64

In [17]:
df.groupby('City')['Revenue'].sum()

City
Ahmedabad    5350
Rajkot       6100
Surat        5100
Name: Revenue, dtype: int64

In [19]:
df.groupby(['City','Product'])['Revenue'].sum()

City       Product
Ahmedabad  Burger     1950
           Pasta      1000
           Pizza      2400
Rajkot     Burger     1050
           Pasta      1750
           Pizza      3300
Surat      Burger      900
           Pasta      1500
           Pizza      2700
Name: Revenue, dtype: int64

In [20]:
# Appply multiple aggregation function 


df.groupby('City')['Revenue'].agg(
    ['sum','max','min']
)

            sum   max  min
City
Ahmedabad  5350   900  250
Rajkot     6100  1500  150
Surat      5100  1200  250

In [22]:
# Different Aggregation for different column

df.groupby('City').agg(
    total_revenue=('Revenue','sum'),
    average_revenue=("Revenue", "mean"),
    total_quantity=("Quantity", "sum"),
    order_count=("OrderID", "count")
)

           total_revenue  average_revenue  total_quantity  order_count
City
Ahmedabad           5350            535.0              25           10
Rajkot              6100            610.0              25           10
Surat               5100            510.0              21           10

In [26]:
df["Month"] = df["Date"].dt.month_name()
df.groupby('Month')['Revenue'].sum()

Month
February    5650
January     4750
March       6150
Name: Revenue, dtype: int64

In [27]:
df[(df['City']=="Rajkot")&(df['Revenue']>500)]

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue,Month
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600,January
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600,January
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900,January
12,1013,2026-02-08,Rajkot,Pasta,Main Course,3,250,Amit,Cash,Delivered,750,February
27,1028,2026-03-22,Rajkot,Pizza,Main Course,5,300,Amit,UPI,Delivered,1500,March

In [29]:
df[df["PaymentMethod"].isin(["UPI", "Card"])]

,OrderID,Date,City,Product,Category,Quantity,UnitPrice,Employee,PaymentMethod,Status,Revenue,Month
0,1001,2026-01-03,Rajkot,Pizza,Main Course,2,300,Amit,UPI,Delivered,600,January
2,1003,2026-01-07,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250,January
3,1004,2026-01-10,Rajkot,Burger,Fast Food,4,150,Amit,UPI,Delivered,600,January
4,1005,2026-01-12,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600,January
6,1007,2026-01-18,Rajkot,Pizza,Main Course,3,300,Amit,UPI,Delivered,900,January
7,1008,2026-01-21,Ahmedabad,Pasta,Main Course,1,250,Neha,UPI,Cancelled,250,January
9,1010,2026-01-28,Rajkot,Pizza,Main Course,1,300,Amit,Card,Delivered,300,January
10,1011,2026-02-02,Ahmedabad,Burger,Fast Food,5,150,Neha,UPI,Delivered,750,February
11,1012,2026-02-04,Surat,Pizza,Main Course,2,300,Rahul,Card,Delivered,600,February
13,1014,2026-02-11,Ahmedabad,Pizza,Main Course,1,300,Neha,UPI,Cancelled,300,February
15,1016,2026-02-17,Rajkot,Pasta,Main Course,2,250,Amit,Card,Delivered,500,February
16,1017,2026-02-20,Ahmedabad,Pizza,Main Course,3,300,Neha,UPI,Delivered,900,February
18,1019,2026-02-25,Rajkot,Burger,Fast Food,1,150,Amit,UPI,Cancelled,150,February
19,1020,2026-02-27,Ahmedabad,Pizza,Main Course,2,300,Neha,Card,Delivered,600,February
20,1021,2026-03-01,Surat,Pizza,Main Course,4,300,Rahul,UPI,Delivered,1200,March
22,1023,2026-03-07,Ahmedabad,Pasta,Main Course,3,250,Neha,Card,Cancelled,750,March
23,1024,2026-03-10,Surat,Pizza,Main Course,1,300,Rahul,UPI,Delivered,300,March
25,1026,2026-03-16,Ahmedabad,Burger,Fast Food,3,150,Neha,Card,Delivered,450,March
26,1027,2026-03-19,Surat,Pizza,Main Course,2,300,Rahul,UPI,Delivered,600,March
27,1028,2026-03-22,Rajkot,Pizza,Main Course,5,300,Amit,UPI,Delivered,1500,March
29,1030,2026-03-28,Surat,Pasta,Main Course,1,250,Rahul,Card,Cancelled,250,March

In [30]:
print(df.isna().sum())
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

OrderID          0
Date             0
City             0
Product          0
Category         0
Quantity         0
UnitPrice        0
Employee         0
PaymentMethod    0
Status           0
Revenue          0
Month            0
dtype: int64